### ISSUE TITLE
upgrade to latest version planned?

### ISSUE THREAD

**Issue by marcotrosi** [sbdchd/homebrew-skim#5]
Hi,
I just wanted to ask if there are any plans to update to the latest skim version?
I would need a fix for a "bug" in version 0.5.2.
Thanks for thinking about it.
marco

**Comment by sbdchd** [comment]
I think skim is now in homebrew proper so it should be updated there. 

https://github.com/Homebrew/homebrew-core/blob/master/Formula/sk.rb

I should also update the readme on this repo and probably archive it as well.

**Comment by marcotrosi** [comment]
> I think skim is now in homebrew proper so it should be updated there.
> 
> https://github.com/Homebrew/homebrew-core/blob/master/Formula/sk.rb
> 
> I should also update the readme on this repo and probably archive it as well.

thank you @sbdchd , I actually thought this repo here is the homebrew repo. Sorry for that.
But one more question if you don't mind. The link you just sent to the sk.rb file, when I look at it, it says ...
url "https://github.com/lotabout/skim/archive/v0.8.2.tar.gz"
Any idea why on my system 0.5.2 is the latest?

**Comment by sbdchd** [comment]
Might need to `brew update` to get the latest versions of the Formula or maybe it's installed via some other method, like cargo.

Edit: or you're using this formula in which case you'll need to remove it and use the homebrew one
